- name: Install Docker
  yum:
    name: docker
    state: present
  become: true

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: true
  become: true

- name: Add ec2-user to docker group
  user:
    name: ec2-user
    groups: docker
    append: yes
  become: true

- name: Install Docker Compose
  shell: |
    curl -fsSL https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64 -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose
  args:
    creates: /usr/local/bin/docker-compose
  become: true
